### ISSUE TITLE
Error with shards loading v0.1.2

### ISSUE THREAD

**Issue by aurelien-ldp** [crystal-lang/crystal-mysql#10]
Hello,
I got this error on the README example:
```
Error in ./libs/db/db/result_set.cr:70: abstract `def DB::ResultSet#read()` must be implemented by MySql::ResultSet

    abstract def read
```

My `shard.yml`:
```
dependencies:
  mysql:
    github: crystal-lang/crystal-mysql
```

But **it does work** when I specify the branch master in `shard.yml`:
```
dependencies:
  mysql:
    github: crystal-lang/crystal-mysql
    branch: master
```

The implementation of `DB::ResultSet` differs from `master` to tag 0.1.2. In the version cloned by `shards` (tag 0.1.2) `DB::ResultSet#read()` is not implemented.

Is it just me or did I miss something ?

Thanks
