### ISSUE TITLE
shards issue

### ISSUE THREAD

**Issue by crisward** [crystal-lang/crystal-mysql#11]
Not sure why but I'm getting this error in my ci.

```
Updating https://github.com/crystal-lang/crystal-mysql.git
Error resolving db (*, ~> 0.2.0)
```

Also happens locally when I run `crystal deps`

**Comment by bcardiff** [comment]
@crisward can you share your shard.yml and lock file?

**Comment by crisward** [comment]
shards.yml
```
name: app
version: 0.1.0

authors:
  - Cris Ward

license: MIT

dependencies:
  kemal:
    github: crisward/kemal
    branch: master
  slang:
    github: jeromegn/slang
    version: ~> 1.4.1
  db:
    github: crystal-lang/crystal-db
    branch: master
  mysql:
    github: crystal-lang/crystal-mysql
    branch: master
  kiwi:
    github: greyblake/crystal-kiwi
    version: ~> 0.1.0
```

shards.lock
```
version: 1.0
shards:
  db:
    github: crystal-lang/crystal-db
    commit: d7fdf1eada852ea084b7b9786e149094ec5270e0

  kemal:
    github: crisward/kemal
    commit: a8cc4f4177745f33fddbdf49472b6c440f607a7c

  kilt:
    github: jeromegn/kilt
    version: 0.3.3

  kiwi:
    github: greyblake/crystal-kiwi
    version: 0.1.0

  mysql:
    github: crystal-lang/crystal-mysql
    commit: c789a1e07b578a7ba46328862732a74b0bd432d9

  radix:
    github: luislavena/radix
    version: 0.3.1

  slang:
    github: jeromegn/slang
    version: 1.4.1
```

**Comment by bcardiff** [comment]
Ok, It seems that shards is not allowing to use `db@master` when there is requirement of `db~>0.2.0` which is coming form `mysql=0.2.0` (or `mysql@master`)

Current alternatives:

```
dependencies:
  db:
    github: crystal-lang/crystal-db
  mysql:
    github: crystal-lang/crystal-mysql
    branch: master
```

```
dependencies:
  db:
    github: crystal-lang/crystal-db
  mysql:
    github: crystal-lang/crystal-mysql
    version: ~> 0.2.0
```

When a 0.2.1 of db is released you should be  able to add that in shard.yml, but `branch: master` seems to not be supported together with `~> 0.2.0`.
